name: Run tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: python3 util/install_deps.py
    - run: pip install .
    - uses: actions/cache@v3
      with:
        key: cache-dir
        path: /home/runner/.cache/simalq
    - run: pip install pytest
    - run: pytest tests
