name: Run tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: ['3.10', 3.11, 3.12, pypy-3.10]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - run: pip install
        pip==24.0 setuptools==69.1.1 wheel==0.42.0 pytest==8.0.2
    - run: python util/install_deps.py
    - run: pip install .
    - uses: actions/cache@v4
      with:
        key: cache-dir
        path: /home/runner/.cache/simalq
    - run: pytest tests
